Espp 686 app example image error url
Elastic-Suite/gally pull request #508
Opened 2023-01-23 17:34 UTC by Ponefar

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-01-26 09:17 UTC, tonai requested changes

2023-01-26 09:17 UTC, tonai commented on front/example-app/src/components/Products/ProductCard.tsx
> +import { useFetchApi } from 'src/hooks'
Utilises des imports relatifs et pas des imports `src/...`

2023-01-26 09:17 UTC, tonai commented on front/example-app/src/components/Products/ProductCard.tsx
> +  const [baseUrl, setBaseUrl] = useState<string>('')
Il ne faut pas dupliquer le state.
La valeur que tu cherches se trouve déjà dans `response`.
Du coup il faut juste définir une valeur calculée:
```js
const baseUrl = response?.data['hydra:member'].find(
  (item) => item.id === 'base_url/media'
).value
```

2023-01-26 09:17 UTC, tonai commented on front/example-app/src/components/Products/ProductCard.tsx
> +  const [response] = useFetchApi<IHydraResponse<any>>('/configurations')
De plus je pense pas que ce soit le bon endroit pour charger cela.
Si tu changes de page produit, tu va re-déclencher un appel AJAX sur `/configurations`.
Il faut charger la configuration dans un contexte comme pour `CatalogProvider` et mettre ce provider dans `AppProvider`.

2023-01-26 09:17 UTC, tonai commented on front/example-app/src/components/Products/ProductCard.tsx
> +  }, [response])
Pas besoin de `useEffect`.

2023-01-26 09:17 UTC, tonai commented on front/example-app/src/components/Products/ProductCard.tsx
> +    baseUrl && (
plutôt que de tout mettre dans un `if` et ajoute un degrés d'indentation tu peux plutôt:
```
if (!baseUrl) {
  return null;
}
```
(mais du coup d'après les autres commentaires ce code doit être dans le Provider)

2023-01-26 09:17 UTC, tonai commented on front/example-app/src/components/Products/ProductCard.tsx
> +  const [response] = useFetchApi<IHydraResponse<any>>('/configurations')
Pour être plus générique le contexte doit fournir toute la configuration et pas uniquement `baseUrl`.

2023-01-26 16:53 UTC, tonai requested changes

2023-01-26 16:53 UTC, tonai commented on front/example-app/src/components/Providers/ConfigurationsProvider/ConfigurationsProvider.tsx
> +    <configurationsContext.Provider value={response?.data}>
Inspire de son qu'on a fait sur pwa.
Pour éviter de faire un `find` afin de récupérer la configuration de la base URL on a créé un objet pour pouvoir directement accéder à `configuration['base_url/media']`:
```js
          Object.fromEntries(
            configurations.data['hydra:member'].map((configuration) => [
              configuration.id,
              configuration.value,
            ])
          )
```
cf https://github.com/Elastic-Suite/gally-admin/blob/1.0.x/packages/components/src/hooks/useDataLoader.ts#L48

2023-02-10 09:08 UTC, botisSmile commented on api/composer.json
> +        "gally/gally-standard": "dev-master",
La version de gally/gally-standard ne doit pas changer, la branche de destination est la 1.0.x

2023-02-14 12:25 UTC, botisSmile commented on api/composer.json
> +        "gally/gally-standard": "dev-master",
La version de gally/gally-standard ne doit pas changer, la branche de destination est la 1.0.x

2023-02-14 16:08 UTC, botisSmile approved these changes

2023-02-15 15:59 UTC, merged